### ISSUE TITLE
How to use with buf

### ISSUE THREAD

**Issue by darkliquid** [knqyf263/go-plugin#73]
I generally tend to use [buf][1] rather than directly calling `protoc`, so I had to do a bit of work to figure out how to make this work with that.

Here's my solution:

`buf.yaml`
```yaml
version: v2
modules:
  - path: proto
```

`buf.gen.yaml`
```yaml
version: v2
clean: true
managed:
  enabled: true
plugins:
  - local: ["go", "tool", "github.com/knqyf263/go-plugin/cmd/protoc-gen-go-plugin"]
    out: pkg
    opt:
      - paths=source_relative
    strategy: directory
    include_imports: true
    include_wkt: true
```

And added the following to my `go.mod` (making use of the new tool directive):
```go.mod
tool (
	github.com/bufbuild/buf/cmd/buf
	github.com/bufbuild/buf/cmd/protoc-gen-buf-breaking
	github.com/bufbuild/buf/cmd/protoc-gen-buf-lint
	github.com/knqyf263/go-plugin/cmd/protoc-gen-go-plugin
)
```

I can now run:

```sh
go tool buf generate
```

And have it generate the code from my `proto` folder into my `pkg` folder.

[1]:https://buf.build/product/cli
